### ISSUE TITLE
频繁翻译出错问题

### ISSUE THREAD

**Issue by Trach7enberg** [Ifan24/youtube_dual_subtitles#10]
1.  有时候连续翻译字幕文件会出现Anthropic's server encountered an error while processing your request. Please try again later,
 	并且如果再次点击翻译missing Line 只会翻译 1 页(30batch size )然后又报同样错误,或者需要等待一段时间才能使用
	> **触发程度**:非常频繁

2. 有时候翻译过程中报错,Token花费了 但是字幕并没有填充,又得重头开始翻译
	> **触发程度**:很少

3. 如果字幕文件中的个别字体出现乱码(比如菱形方块问号),那么翻译会无法进行需要手动删除
 	> **触发程度**:很少

**剩余Token**:充足
**账户订阅**:基础会员
**翻译类型**:英文->简体中文
**使用模型**:claude-3-Haiku、claude-3-Sonnet

**Comment by Ifan24** [comment]
感谢反馈！

1. 关于频繁出现的这个错误：
> Anthropic's server encountered an error while processing your request. Please try again later

这个错误通常是由于 Claude API 在高峰期出现超载导致的。推荐是如果碰到了就换一个模型进行翻译，比如换到免费的Gemini或者gpt3.5，或者稍微等一会，对于翻译"missing Line" 功能，它设计为只翻译尚未翻译的字幕，并使用上下文辅助翻译，如果只翻译1页可能是因为只剩下那一页还没有翻译了

2. 关于翻译过程中报错，Token 已消耗但字幕未填充的问题：

这个问题可能是由于模型输出格式不正确（非 JSON 格式）或拒绝回答造成的。我们实施了一些后处理代码来修正轻微的 JSON 格式错误，降低了问题发生的频率，但是还是有小概率发生，而且如果发生了就提取不出翻译。由于 Claude 的计费规则是一旦请求发出就会收取全部费用，无法中途中断，确实挺烦的，推荐是遇到这些格式不正确的时候换成免费的Gemini来翻译剩下的

3. 关于字幕文件中出现乱码导致无法翻译的问题：

这个错误确实是第一次见，我自己的测试了一下加入大量的特殊符号 比如说这个`�`，似乎还是可以提取出翻译的，不知道是那一个符号造成了这个错误，但是如果遇到的话，一般换一个模型，或者把随机性调高一些通常能够解决问题
