### ISSUE TITLE
多文件同时翻译

### ISSUE THREAD

**Issue by Trach7enberg** [Ifan24/youtube_dual_subtitles#12]
字幕文件太多了,一个一个选太慢,请问可以支持多文件同时翻译吗,多开网页同时翻译会报错

**Comment by Ifan24** [comment]
感谢反馈和建议! 我把同时处理多文件加到的开发计划中了

在实现这个功能之前，可以试一下临时的解决方案：同时打开多个页面，在每个页面中翻译一个文件。理论上应该是可行的，因为每个翻译任务都是独立进行的，除非是遇上速率限制之类的错误

我刚刚试了一下，同时打开了4个页面，每个页面翻译一个不同的字幕文件。用了一样的翻译设置 （批处理大小为50，模型选择Gemini-flash），差不多同一时间点翻译，似乎没有遇到错误

所以请问可以提供一些更多的报错信息吗？比如错误信息和同时翻译了几个项目之类的

**Comment by Trach7enberg** [comment]
同时翻译3到5个文件,每个文件大概200行到400行,选用Claude模型貌似同一时间只能翻译一个
用的是Claude-3-Haiku、sonnet 会频繁报错 

Error: Maximum tokens reached. Unable to parse the response 
①Please reduce the batch size in the advanced settings and try again

②Anthropic's server encountered an error while processing your request. Please try again later

现在切换到GPT-4o和GPT-4oMini暂时没问题

**Comment by Ifan24** [comment]
> Error: Maximum tokens reached. Unable to parse the response
①Please reduce the batch size in the advanced settings and try again

这个错误是因为达到这个模型的最大生成上限了，claude-haiku只有4096的生成Token，所以如果开反思模式或者批处理大小>40的话就很容易出错，GPT-4o-mini会好一些，生成上限是16k，所以一般不会有这个错误

> ②Anthropic's server encountered an error while processing your request. Please try again later

这个是因为Anthropic的服务器过载了，我翻了下claude的log，还蛮随机的这个报错，500个请求里有大概10次左右，都是集中在差不多一个时间段的，所以除了等一段时间也没什么办法，或者用其他模型也行
