### ISSUE TITLE
同时翻译多个文件,CPU会占用过高 ,Having multiple browser translation pages open at the same time is causing high CPU usage and making the browser lag (this didn't happen before)

### ISSUE THREAD

**Issue by Trach7enberg** [Ifan24/youtube_dual_subtitles#13]
现在同时翻译多个文件会造成页面卡顿,比如下载翻译文件时选择双语还是单语选项的按钮点击选择时会卡顿
图片是同时翻译13个文件,已翻译完成3个时CPU的占用
![a03cf8bfd22a4309ff9902f2ee1be86](https://github.com/user-attachments/assets/263c76b2-dc85-43b2-9085-4467f479270b)

**Comment by Ifan24** [comment]
你好，

这个高 CPU 使用率的问题可能是由"预估消耗 Token"功能导致的。目前这个功能会随着内容的变化不断计算预估的 Token 消耗，特别是在同时处理多个文件时，可能会导致较高的 CPU 占用和界面卡顿。

计划在下一个版本中这样改应该可以解决这个问题：

1. 默认情况下不会自动计算 Token 预估消耗。
2. 添加一个专门的按钮来显示和计算 Token 预估消耗。
3. 或者在点击"开始翻译"时才显示预估消耗。

感谢反馈。如果有任何其他问题或建议，可以随时回复我。
