### ISSUE TITLE
在翻译时如何处理断句问题？

### ISSUE THREAD

**Issue by qazwsdc** [Ifan24/youtube_dual_subtitles#14]
whisper生成的字幕经常出现断句问题，一个完整的句子被分割。比如：
1
00:00:00,000 --> 00:00:05,000
I am

2
00:00:05,000 --> 00:00:08,000
boy
这样在翻译时会出现上下文不连贯。
不知道该项目是如何处理这个问题的呢

**Comment by Ifan24** [comment]
感谢反馈！在我的新项目 [GPTSubtitler](https://gptsubtitler.com) 里，专门针对Whisper的断句问题弄了个"流畅合并"模式来改善。

该模式会在提示词中加上这些指令+相关的少样本示例来指导语言模型处理断句：

- If a subtitle text at a given index is short (less than 4 words) and its meaning is closely connected to the previous or next subtitle, you may combine it with the adjacent subtitle's translation for a more fluent result.
- When combining subtitles, output the full translation in the first subtitle of the group, and use ellipsis '...' for the subsequent combined subtitles.
- If a short subtitle (less than 4 words) is followed by a longer, closely related subtitle, combine them and put the full translation in the short subtitle's slot, using '...' for the longer subtitle.
- Use this technique judiciously. Only combine subtitles when it significantly improves the fluency and naturalness of the translation without losing any important information or timing cues.
- Never skip or omit the translation of any subtitle entirely. All information from the original subtitles should be represented in the translation.
- When combining subtitles, ensure that the resulting translation doesn't become excessively long, which could make it difficult for viewers to read in the given time.
- Be mindful of the context and ensure that combining subtitles doesn't lead to confusion or loss of emphasis present in the original subtitles.
- Always prioritize maintaining the original subtitle structure unless combining significantly improves fluency.
- Never use '...' for subtitles longer than 4 words.


## 示例效果

以提供的例子为例：

**原始字幕：**
```
1
00:00:00,000 --> 00:00:05,000
I am

2
00:00:05,000 --> 00:00:08,000
boy
```

**语言模型翻译后：**
```
1
00:00:00,000 --> 00:00:05,000
我是男孩

2
00:00:05,000 --> 00:00:08,000
...
```

**导出 SRT 文件后（启用"移除空行"功能）：**
```
1
00:00:00,000 --> 00:00:08,000
我是男孩
```

## 局限性

这些指令在大多数情况下都能很好地处理断句问题。但偶尔可能会出现将较长句子也合并的情况，因为翻译后形成了一个完整句子。这种情况下较长的句子会变成"..."，有时就需要手动修改，但一般越厉害的大模型就越不容易出错

可能还有更好的处理方案，比如直接把whisper生成的字幕预处理，把短的断句和上一句融合之后再翻译，但这需要有每个词的时间戳，有一些局限性我就没有继续探索这个方向了

**Comment by qazwsdc** [comment]
我也想过预处理whisper生成的字幕，但就像你说的，需要具体的时间戳才可以实现……所以目前似乎也没有更好的方案了

您的新项目 [GPTSubtitler](https://gptsubtitler.com/) 是否有开源翻译部分的代码呢

**Comment by Ifan24** [comment]
目前暂时没有开源的打算欸。翻译部分除了翻译功能外，还包含了很多与前端交互、数据库操作、用户管理等模块，这些部分都是紧密耦合的，不太容易单独拆分出来。

不过如果对具体的翻译处理感兴趣的话，可以去试用一下，网站的提示词和少样本示例都是公开且可以调整的，所以想要复刻应该也不是很难
