### ISSUE TITLE
for translation does it support gpt 4o and gpt 4?

### ISSUE THREAD

**Issue by fahd200581** [Ifan24/youtube_dual_subtitles#9]
for translation does it support gpt 4o and gpt 4?

**Comment by Ifan24** [comment]
Hi, you can use the gpt-4o or gpt 4 model by using the `-m` flag or change the default model here:
https://github.com/Ifan24/GPT_subtitles/blob/a9eef4deedefc15b8e85e9e27d4241a219856700/translate_gpt.py#L667
